services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/djangoApp
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/petproject
      - REDIS_URL=${LOCATION}

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
    ports:
      - ${PORT}:5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
