services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/djangoApp
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/petproject
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petproject
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  redis:
    image: redis:7
    restart: always
    

volumes:
  postgres_data:
