services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/djangoApp
    depends_on:
      - db
      - redis
    entrypoint: ['dockerize', "-wait", "tcp://db:5432", "-timeout", "60s", "python", "manage.py", "runserver", "0.0.0.0:8080"]
    environment:
      - DEBUG=True

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.0.15
    restart: always
    ports:
      - "6379:6379"
  
  test:
    build: 
      context: .
      dockerfile: dockerfile.test
    command: dockerize -wait tcp://db:5432 -timeout 60s pytest -rP
    volumes:
      - .:/code
    depends_on:
      - db
      - web
    environment:
      - DEBUG=True

volumes:
  postgres_data:
