# Generated by Django 5.1.4 on 2025-01-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['title']},
        ),
    ]
