# Generated by Django 5.1.4 on 2025-01-10 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_alter_comment_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['comment'], name='djangoApp_c_comment_5f66a7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['title', 'description'], name='djangoApp_t_title_28a501_idx'),
        ),
    ]
