# Generated by Django 5.1.4 on 2025-01-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_alter_author_options_alter_ticket_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='djangoApp_c_comment_5f66a7_idx',
        ),
    ]
