name: Deploy to server

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKET_USERNAME }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            scripts: |
                sudo rm -rf DjangoProj
                mkdir DjangoProj
                cd DjangoProj
                git clone https://github.com/Siroj099/DjangoProj.git .
                docker build -t Siroj099/DjangoProj:latest .
                docker push Siroj099/DjangoProj:latest
                sudo docker compose down
                sudo docker compose up -d --build
                sudo docker exec django-DjangoProj python manage.py migrate
                sudo docker exec django-DjangoProj python manage.py collectstatic --noinput

         