name: Deploy to server

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
            password: ${{ secrets.DOCKER_PASSWORD }}
            username: ${{ secrets.DOCKER_USERNAME }}

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
                sudo rm -rf DjangoProj
                mkdir DjangoProj
                cd DjangoProj
                git clone https://github.com/Siroj099/DjangoProj.git .
                docker build -t siroj099/djangoapp:latest .
                docker push siroj099/djangoapp:latest
                sudo docker compose down
                sudo docker compose up -d --build
                sudo docker exec djangodroj-web-1 python manage.py migrate
                sudo docker exec djangoproj-web-1 python manage.py collectstatic --noinput

         